# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concentracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_farmacia', models.CharField(max_length=30)),
                ('descuento', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('codigo_medicamento', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=50)),
                ('precio2013', models.FloatField()),
                ('precio2014', models.FloatField()),
                ('precio2015', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SeVende',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variacionMedicamentos.Farmacia')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variacionMedicamentos.Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Tiene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variacionMedicamentos.Concentracion')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variacionMedicamentos.Medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='concentraciones',
            field=models.ManyToManyField(through='variacionMedicamentos.Tiene', to='variacionMedicamentos.Concentracion'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='medicamentos',
            field=models.ManyToManyField(through='variacionMedicamentos.SeVende', to='variacionMedicamentos.Medicamento'),
        ),
    ]
