# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variacionMedicamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anios',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='precio_anios',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='precio_anios',
            name='medicamento',
        ),
        migrations.AddField(
            model_name='med_concentracion',
            name='precio13',
            field=models.FloatField(default=7.7, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='med_concentracion',
            name='precio14',
            field=models.FloatField(default=0.8, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='med_concentracion',
            name='precio15',
            field=models.FloatField(default=0.9, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Anios',
        ),
        migrations.DeleteModel(
            name='Precio_anios',
        ),
    ]
