# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variacionMedicamentos', '0003_auto_20160619_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmacia',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='concentraciones',
        ),
    ]
