# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variacionMedicamentos', '0004_auto_20160619_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='med_concentracion',
            name='precio13',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='med_concentracion',
            name='precio14',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='med_concentracion',
            name='precio15',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
