# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authent.Department'),
        ),
    ]
